import './globals.css'
import NavBar from './NavBar'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'הכנה למבחןב עיצוב מערכות מידע',
  description: 'Generated by create next app',
}
import ReactGA from 'react-ga';
ReactGA.initialize('G-TK3VW8QD0H');
export default function RootLayout({ children }) {
  return (
<html lang='en' >
<body>
  {children}  
</body>

   </html>
  )
}
