import './globals.css'
import NavBar from './NavBar'
import { Inter } from 'next/font/google'
import ReactGA from 'react-ga';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'הכנה למבחן עיצוב מערכות מידע',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
ReactGA.initialize('G-TK3VW8QD0H');

  return (
<html lang='en' >
<body>
  {children}  
</body>

   </html>
  )
}
